### ISSUE TITLE
Ошибка при запуске.

### ISSUE THREAD

**Issue by IntelOut** [nazmiev/Tinkoff-stream-grid-bot#4]
Где-то не хватает аргумента походу...
Хотя частично заявки выставляются.

```
Traceback (most recent call last):
  File "Tinkoff-stream-grid-bot.py", line 287, in <module>
    sys.exit(main())
  File "Tinkoff-stream-grid-bot.py", line 121, in main
    for response in client.orders_stream.trades_stream():
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tinkoff/invest/_errors.py", line 43, in wrapper
    yield from func(*args, **kwargs)
TypeError: trades_stream() missing 1 required positional argument: 'accounts'
```

**Comment by nazmiev** [comment]
У вас где-то не хватает account id.
У меня к каждой акции в словарике прописан номер счета.
Если у вас он один, то можете так же как и токен прописать его в соседнем txt,

Но тогда надо будет много где поправить.

**Comment by nazmiev** [comment]
А, нет!
они обновили библиотеку, а я нет.
Теперь для стрима нужно передавать номер счета.

поправлю и залью до вторника 17.05.2022

https://github.com/Tinkoff/invest-python/blob/0a1f5020053cbf16297355a98ada8361aa8b4955/tinkoff/invest/services.py#L950

**Comment by IntelOut** [comment]
Также вышибает все тейк-профиты и стоп-лоссы на акке... ><
Или это фича такая?

**Comment by nazmiev** [comment]
Фича, удобно при перезапуске бота чтоб он отменил предыдущие ордера. Руками их долго отменять.

Можно закомментировать там строчку cancel orders

**Comment by nazmiev** [comment]
Вообще с текущей обстановкой на рынках я написал другого бота:
Он по утрам выставляет ордера по самому низу рынка.
Поделюсь им в ближайшее время

**Comment by nazmiev** [comment]
Всё проверил — работает.
Ордера выставляются, за ордерами следит.

чтобы не отменяли все тейки закоментируйте строку 
client.cancel_all_orders(account_id=account_id)

**Comment by IntelOut** [comment]
А в .py файл запушили изменения, если они были? Он не изменился.
у меня та же ошибка продолжает вылетать
